---
- name: foo
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Gather some facts
      setup:
        filter: ansible_*

  roles:
    - madness
