---
- name: Clone
  git:
    repo: https://github.com/hoaile1/dotfiles.git
    dest: "{{ ansible_user_dir }}/dotfiles"
    accept_hostkey: true

- name: Symlink dotfiles
  file:
    src: "{{ ansible_user_dir }}/dotfiles/{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - .gitconfig
    - .git-promp-colors.sh
    - .vimrc
