---
- name: Symlink dotfiles
  file:
    src: "{{ ansible_user_dir }}/dotfiles/{{ item }}"
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - .gitconfig
    - .git-prompt-colors.sh
    - .vimrc
