---
- name: Install development tools
  package:
    name: "@Development tools"
  become: true
  when: ansible_os_family == "RedHat"

- name: Install development tools
  apt:
    name: build-essential
  become: true
  when: ansible_os_family == "Debian"
