---
- name: Install development tools
  dnf:
    name: "{{ dev_pkgs }}"
  become: true

- name: Install virtualenv and virtualenvwrapper
  pip:
    name: "{{ pip_pkgs }}"
    state: latest
  become: true

- name: Download keychain
  get_url:
    url: "{{ keychain_url }}"
    dest: "/tmp/{{ keychain_archive }}"

# FIXME: Seems like this task isn't perfect.
- name: Unarchive keychain
  unarchive:
    src: "/tmp/{{ keychain_archive }}"
    dest: "/tmp"

- name: Copy keychain to /usr/bin
  copy:
    src: "/tmp/{{ keychain_dir }}/keychain"
    dest: /usr/bin/keychain
    mode: 0755
  become: true
