---
- name: Install development tools
  dnf:
    name: "{{ item }}"
  loop:
    - "@Development tools"
    - libselinux-python
    - rubygems
    - vim-X11
    - python-pip
  become: true

- name: Install virtualenv and virtualenvwrapper
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - pip
    - virtualenv
    - virtualenvwrapper
  become: true

- name: Create a directory for virtualenvwrapper
  file:
    path: ~/Envs
    state: directory

- name: Install keychain
  get_url:
    url: "{{ keychain_url }}"
    dest: "/tmp/{{ keychain_archive }}"

- name: Unarchive keychain
  unarchive:
    src: "/tmp/{{ keychain_archive }}"
    dest: /tmp

- name: Copy keychain to /usr/bin
  copy:
    src: "/tmp/{{ keychain_dir }}/keychain"
    dest: /usr/bin/keychain
  become: true
