---
- name: Install development tools
  package:
    name: "{{ item }}"
  with_items:
    - "@Development tools"
    - libselinux-python
    - rubygems
  become: true
  when: ansible_os_family == "RedHat"

- name: Install development tools
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - python-selinux
  become: true
  when: ansible_os_family == "Debian"

- name: Install keychain
  get_url:
    url: "{{ keychain_url }}"
    dest: "/tmp/{{ keychain_archive }}"

- name: Unarchive keychain
  unarchive:
    src: "/tmp/{{ keychain_archive }}"
    dest: "/tmp/{{ keychain_dir }}"

- name: Copy keychain to /usr/bin
  copy:
    src: "/tmp/{{ keychain_dir }}/keychain"
    dest: /usr/bin/keychain
