---
- name: Download the zsh archive
  get_url:
    url: "{{ zsh_url }}"
    dest: "~/Download/{{ zsh_archive }}"

- name: Unarchive the package
  unarchive:
    src: "~/Download/{{ zsh_archive }}"
    dest: "~/Download/{{ zsh_dir }}"

- name: Configure, compile, and install Zsh
  command: "{{ item }}"
  args:
    chdir: "~/Download/{{ zsh_dir }}"
  loop:
    - ./configure
    - make
    - sudo make install
